services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_DOCKER}
      POSTGRES_DB: ${DATABASE_NAME_DOCKER}
      POSTGRES_USER: ${DATABASE_USERNAME_DOCKER}
    ports:
      - 5432:5432

  api:
    build:
      context: ./server
      target: ${NODE_ENV}
    depends_on:
      - database
    ports:
      - ${API_PORT}:3000
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:3000
    env_file:
      - .env
