services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tms
    ports:
      - 5432:5432

  api:
    build:
      context: ./server
      target: ${NODE_ENV}
    restart: always
    depends_on:
      database:
        condition: service_started
        required: true
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env

  frontend:
    environment:
      - NEXT_PUBLIC_API_URL=arbitrary_value
    build:
      context: ./frontend
    ports:
      - 80:3000
    env_file:
      - .env
